apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo
data:
  nginx.conf: |-
    server {
      listen 0.0.0.0:{{ .Values.nginxService.internalPort }};
      root /app;
      location / {
        index index.html index.php;
      }
      location ~ \.php$ {
        fastcgi_pass {{ template "fullname" . }}-phpfpm:9000;
        fastcgi_index index.php;
        include fastcgi.conf;
      }
    }
