apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: nginx
  selector:
    app: nginx
