apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  namespace: demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  type: ClusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: phpfpm
  selector:
    app: phpfpm
